DROP DATABASE IF EXISTS EMP_CMS2_db;
CREATE DATABASE EMP_CMS2_db;

USE EMP_CMS2_db;

CREATE TABLE Departments (
dep_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
dep_name VARCHAR(30) NULL 
);

USE EMP_CMS2_db;

CREATE TABLE Roles (
role_id INTEGER AUTO_INCREMENT PRIMARY KEY, 
title VARCHAR(30) NULL, 
salary DECIMAL(9,2) NULL, 
dep_id INTEGER NULL
  
);

USE EMP_CMS2_db;

CREATE TABLE Employees (   
emp_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL, 
first_name VARCHAR(30) NULL, 
last_name VARCHAR(30) NULL, 
role_id INTEGER NULL,
manager_id INTEGER NULL

);

