DROP DATABASE IF EXISTS EMP_CMS2_db;
CREATE DATABASE EMP_CMS2_db;

USE EMP_CMS2_db;

CREATE TABLE Departments (
dep_id INTEGER AUTO_INCREMENT PRIMARY KEY,
dep_name VARCHAR(30) NOT NULL 
);

USE EMP_CMS2_db;

CREATE TABLE Roles (
role_id INTEGER AUTO_INCREMENT PRIMARY KEY, 
title VARCHAR(30) NOT NULL, 
salary DECIMAL(9,2) NOT NULL, 
is_manager TINYINT(1), 
dep_id INTEGER, 
  
FOREIGN KEY(dep_id) REFERENCES Departments(dep_id)

ON DELETE SET NULL 
);

USE EMP_CMS2_db;

CREATE TABLE Employees (   
emp_id INTEGER AUTO_INCREMENT PRIMARY KEY, 
first_name VARCHAR(30) NOT NULL, 
last_name VARCHAR(30) NOT NULL, 
role_id INTEGER,
manager_id INTEGER,
 
FOREIGN KEY (role_id) REFERENCES Roles(role_id),
FOREIGN KEY (manager_id) REFERENCES Employees(emp_id)

ON DELETE SET NULL
);

